### ISSUE TITLE
Patch Before or After Merge?

### ISSUE THREAD

**Issue by Ledicat** [Ledicat/Tafe17S201#3]
Enquire as to whether or not the patch needs to be created before the merge, or if the merge can be done first and then a change made to create a patch file.

**Comment by Ledicat** [comment]
Response from KT when initial question presented: 

> The patch has to be generated before the commit. Patch means "the difference of the codes". Once when the working directory is committed, there is not difference of the codes. You just need to show me (with screen shots) on any version of the patch and able to check out the base version to apply the patch will do.

I'm still... confused. If someone else sees KT during the week, could they please try and clarify? Thanks.

**Comment by tafesakt** [comment]
Re: "Enquire as to whether or not the patch needs to be created before the merge".
Yes, the merge can be done before the patch is generated. Therefore when the patch is generated, the patch will include the merged codes as well.

The rule is: if you do not commit the codes after the merge, you still have the differences of the code sitting on local working folder. The patch will include those changes.

**Comment by ffe2d77f** [comment]
"Patch files are simply Unified-Diff files showing the differences between your working copy and the base revision." https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-patch.html

Does this patch needs to be applied or just created for the sake of the exercise?

**Comment by Ledicat** [comment]
TortoiseGit lets us create patches after commits, so we are fine to merge.
