### ISSUE TITLE
Wiki and Website Breakdown?

### ISSUE THREAD

**Issue by Ledicat** [Ledicat/Tafe17S201#4]
Asking about the wiki and website - do we need to cover the Finance features in the wiki, or just the parts that we have developed? 

Also, who will cover what in the website and wiki?

**Comment by Ledicat** [comment]
KT has said just the parts of the project we created, as well as application definition, glossary of terms, member structures etc. 

Michelle will take screenshots of the program to upload to the website branch, Salvador will take it from there.

**Comment by Ledicat** [comment]
I've created the wiki page for the Personal Details feature and KT has okayed its layout and information, so if you want to copy its markdown for your own features, feel free.  Hurrah for consistency. 

Also created the Group Structure wiki page and linked the Personal Details feature to it, if you could do the same when your feature pages are done that would be great.  Same with the Application Definition, just link over the feature after you've created the page. 

I think it's mostly just the glossary, main wiki page and website left now?

**Comment by ffe2d77f** [comment]
Ok, great! I will use your wiki as a template. I am planning to do the website today and right after that, I will do my section of the wiki.

So that would leave the glossary. Do you have any suggestions for that?

**Comment by Ledicat** [comment]
I have a prac this afternoon and can give the glossary a look. It's really
trying to come up with terms to define that's stumping me. It's such a
simple app...

**Comment by ffe2d77f** [comment]
I have pushed the first draft of the website. I would like to hear your thoughts.

**Comment by Ledicat** [comment]
Looking nice and clean, just a few ideas/notes: 

- Start Finance, not Star Finance
- Maybe add quick links to the three different features below the title?
- Instead of 'this feature's interface...' (which needs an apostrophe if it's kept that way) make it a bit more active/direct in language... perhaps something like this:
-- Personal Details: "Manage multiple sets of personal details" then an in-line bullet list of features (add, edit, delete, stored on local device)
-- Contact Details: "Manage multiple contacts' information" then the same bullet list as Personal Details
-- Shopping List: "Keep track of items you intend to purchase" then the bullet list. 
- A link to the gitHub repo page and the wiki main page

The wording above is rough, but if you look at (for example) [https://notepad-plus-plus.org/features/], all the features are listed very directly and assuming that the user is already using it - it's a psychological trick. 

What do you think? It's looking good!

**Comment by ffe2d77f** [comment]
Ok, thanks for that. I’m on it.

**Comment by ffe2d77f** [comment]
Alright all done, What do you think now?

**Comment by ffe2d77f** [comment]
My wiki is all good to go too.

**Comment by Ledicat** [comment]
Thanks for the wiki page, I've created the main wiki page as well as the glossary and added a few things to it - if you can think of anything to add to the glossary, feel free. Your wiki page has been linked from the main page as part of that. 

I'm thinking maybe turn the description of the feature into a h3 and remove the align-left on it, and then turn the 'features' title into a h4 and add both of those to the same css class as h2 (it's just font-weight:lighter) it might look a little more cohesive. 

![image](https://user-images.githubusercontent.com/14834449/30633109-a1c8504e-9e29-11e7-9746-f79736e92781.png)

Like that, perhaps? 

If you think those are changes worth making and make them, then maybe afterwards we wait for @LostPleb to weigh in before making any more changes. Might have completely different opinions. 

I'm not going to be at my PC from now until late tonight, so no changes will be made from my end. Thanks for doing this.

**Comment by ffe2d77f** [comment]
Ok, no worries. I'll make the changes and push them shortly.

**Comment by LostPleb** [comment]
hi guy's completed my wiki and i'm happy with website.

**Comment by Ledicat** [comment]
I have linked the wiki pages together, good work all. I think the only thing left to do is merge the website back into the gh-pages branch (that's the one that github redirects to for the URL). Alternatively we could just copy/paste the index.html file over since that's the only file that's different I think?

**Comment by ffe2d77f** [comment]
Great! I have merged with master just for the sake of practice. Have a good weekend!

**Comment by Ledicat** [comment]
It shouldn't have been merged with the master, but rather gh-pages. Can you roll-back, please.

To elaborate: The master should be for the project only, not the web page and its files. They belong only in the gh-pages branch.

**Comment by ffe2d77f** [comment]
Oh yeah, I did not know there was a convention for that.
I will roll-back and merge it with gh-pages.

**Comment by Ledicat** [comment]
Excellent, thanks! The URL now works for the website and everything else is linked up. I'll close this issue and zip the master branch to upload to moodle. Thank you both of you again - everything's looking good!
